### ISSUE TITLE
Reuse des Players wird abgelehnt

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/verona-player-simple#10]
Die Verona-Spec sieht vor, dass ein Player nicht immer neu created werden muss, sondern mit einem neuen vopStartCommand neue Unitdaten erhält. Dieser Simple-Player lehnt das ab (Fehler falsche SessionId).

**Comment by paflov** [comment]
Wozu ist die SessionId dann gut, wenn sie nicht überprüft werden muss?

**Comment by mechtelm** [comment]
Die SessionId im vopStartCommand ist immer neu und muss nicht überprüft werden. 

Bei einem vopPageNavigationCommand und vopNavigationDeniedNotification sollte die SessionId vom Player überprüft werden, damit sichergestellt ist, dass diese nicht für eine andere Session gedacht sind. Und mit der SessionId sind natürlich auch die Antworten markiert, damit die Zuordnung zur Unit sichergestellt ist (sonst Probleme beim schnellen Blättern oder bei mehreren Player-Instanzen pro Host-Seite).
