### ISSUE TITLE
Player meldet (unregelmäßig) eine falsche Session-ID

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/verona-player-simple#11]
Steps:
- Frische Testcenterinstallation (beinhaltet Beispielunits mit Simple-Player)
- Login als Beispielnutzer (test)
- Test laden
- ggf. Test erneut laden (Klick auf IQB-Logo und dann "Test fortsetzen")

Verhalten:
Es erscheint ab und zu (nicht bei jedem Versuch, aber reproduzierbar) auf der Konsole eine Fehlermeldung. Siehe Screenshot anbei.
Hat keine sichtbar Auswirkung auf das Verhalten in der Anwendung. Aber Fehler auf der Konsole sind trotzdem zu vermeiden.

![image](https://user-images.githubusercontent.com/446878/228542948-ddf78dbc-e7d2-46a5-8dce-84c20f3ea675.png)

**Comment by paflov** [comment]
Sollte mit diesem Commit behoben sein:
https://github.com/iqb-berlin/verona-player-simple/commit/cd05aa9482b9fce73e80bcbe5486525b3b04d9bf
