### ISSUE TITLE
Navigations-Pfeile optional

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/verona-player-simple#9]
Bei der Darstellung auf mobilen Geräten ist der Bildschirm zu schmal, um rechts und links die Navigationspfeile zeigen zu können. Es sollte einen Weg geben, sie nach Bedarf auszublenden.

**Comment by paflov** [comment]
Der Weg wäre wohl über einen Booklet-Paramater, der mittels einer geeigneten Verona-Erweiterung an den Player weiter gereicht wird. z.B. in der playerConfig.showInteralUnitNavigation.

**Comment by paflov** [comment]
Den gibt es: Einfach folgende Zeile in die Unit-Definition mit aufnehmen:
<style> .vsp-navigation-tier {display: none}</style>
